apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  namespace: bridget
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: tanzu-java-web-app
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: gitops_server_address
    value: ssh://git@github.com
  - name: gitops_ssh_secret
    value: gitops-ssh
  - name: gitops_repository_owner
    value: Mpluya
  - name: gitops_repository_name
    value: config-tanzu-java-web-app-1.3
  - name: gitops_branch
    value: main
  source:
    git:
      url: ssh://git@github.com/Mpluya/tanzu-java-web-app-1.3
      ref:
        branch: main
